# Generated by Django 4.0.4 on 2022-04-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_amountingredient_recipe_amountingredient_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
