# Generated by Django 4.0.4 on 2022-04-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/recipes_image/', verbose_name='Картинка рецепта'),
        ),
    ]
