# Generated by Django 4.0.4 on 2022-04-28 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amountingredient',
            options={'verbose_name': 'Кол-во ингредиента', 'verbose_name_plural': 'Кол-во ингредиентов'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Быстрее чем за 1 минуту кроме бутерброда ничего не приготовить. Укажи время больше одной минуты!')], verbose_name='Время приготовления'),
        ),
    ]
