# Generated by Django 4.0.4 on 2022-04-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_favorite_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'В корзине'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': ('Избранный рецепт',), 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
